import { github } from "@/lib/adapters/github";
import { loadRuleset } from "./ruleset-loader";
import type { Review } from "./types";

const VERDICT_BADGE: Record<Review["verdict"], string> = {
  BLOCK: "🛑 **BLOCK**",
  REQUEST_CHANGES: "✋ **REQUEST CHANGES**",
  APPROVE_WITH_NITS: "✅ **APPROVE (with nits)**",
  APPROVE: "✅ **APPROVE**",
  INSUFFICIENT_INFO: "❓ **INSUFFICIENT INFO**",
};

type EnrichedFinding = Review["results"][number]["findings"][number] & { workflowId: number; workflowTitle: string };

function renderFinding(f: EnrichedFinding, rule: { enforcement: string; text: string } | undefined, opts: { showEnforcement?: boolean } = {}): string[] {
  const out: string[] = [];
  const head = opts.showEnforcement
    ? `**${f.ruleId}** · W${f.workflowId} · ${rule?.enforcement ?? ""}`
    : `**${f.ruleId}** · W${f.workflowId}`;
  out.push(`- ${head} — _${truncate(rule?.text ?? "", 180)}_`);
  if (f.issue) out.push(`  - **Issue:** ${truncate(f.issue, 360)}`);
  if (f.location) out.push(`  - **Where:** \`${truncate(f.location, 160)}\``);
  if (f.fix) out.push(`  - **Fix:** ${truncate(f.fix, 500)}`);
  if (f.evidence) out.push(`  - **Evidence:**\n    > ${truncate(f.evidence, 300).replace(/\n/g, "\n    > ")}`);
  return out;
}

export function buildSummaryMarkdown(review: Review): string {
  const ruleset = loadRuleset();
  const lines: string[] = [];

  lines.push(`## CTO Brain — PR Review`);
  lines.push("");
  lines.push(`**Verdict:** ${VERDICT_BADGE[review.verdict]}`);
  lines.push(`**Classification (R1.7):** \`${review.classification}\``);
  lines.push(`**Workflows applied:** ${review.workflowsRun.join(", ")} _(of ${ruleset.workflows.length})_`);
  lines.push("");
  lines.push(review.summary);
  lines.push("");

  const allFindings: EnrichedFinding[] = review.results.flatMap((r) => r.findings.map((f) => ({ ...f, workflowId: r.workflowId, workflowTitle: r.workflowTitle })));
  const blocking = allFindings.filter((f) => f.status === "fail" && f.severity === "blocking");
  const warnings = allFindings.filter((f) => f.status === "fail" && f.severity === "warning");
  const nits = allFindings.filter((f) => f.status === "fail" && f.severity === "nit");
  const totalFail = blocking.length + warnings.length + nits.length;

  lines.push(`**Findings:** ${blocking.length} blocking · ${warnings.length} warning · ${nits.length} nit · ${allFindings.length - totalFail} pass/na`);
  lines.push("");

  if (blocking.length) {
    lines.push(`### 🛑 Blocking (${blocking.length}) — must fix before merge`);
    for (const f of blocking) {
      lines.push(...renderFinding(f, ruleset.byId.get(f.ruleId), { showEnforcement: true }));
    }
    lines.push("");
  }

  if (warnings.length) {
    lines.push(`### ⚠️ Warnings (${warnings.length}) — should fix or justify`);
    for (const f of warnings) {
      lines.push(...renderFinding(f, ruleset.byId.get(f.ruleId)));
    }
    lines.push("");
  }

  if (nits.length) {
    lines.push(`<details><summary>📝 Nits (${nits.length})</summary>`);
    lines.push("");
    for (const f of nits) {
      lines.push(...renderFinding(f, ruleset.byId.get(f.ruleId)));
    }
    lines.push("");
    lines.push("</details>");
    lines.push("");
  }

  lines.push("<details><summary>Per-workflow summary</summary>");
  lines.push("");
  for (const r of review.results) {
    const fails = r.findings.filter((f) => f.status === "fail").length;
    const passes = r.findings.filter((f) => f.status === "pass").length;
    const nas = r.findings.filter((f) => f.status === "na").length;
    lines.push(`- **W${r.workflowId} ${r.workflowTitle}** — ${passes} pass / ${fails} fail / ${nas} n/a (${r.findings.length} rules)`);
  }
  lines.push("");
  lines.push("</details>");
  lines.push("");
  lines.push("---");
  lines.push(`<sub>Generated by CTO Brain. Evaluated ${allFindings.length} rules from CODE_REVIEW_RULESET.md (${ruleset.totalRules} rules across ${ruleset.workflows.length} workflows). Comment-only review; merge state untouched.</sub>`);

  return lines.join("\n");
}

function truncate(s: string, n = 220): string {
  if (s.length <= n) return s;
  return s.slice(0, n - 1).trimEnd() + "…";
}

export async function postReview(repo: string, prNumber: number, review: Review): Promise<{ url: string }> {
  return github.postReviewComment(repo, prNumber, buildSummaryMarkdown(review));
}
