import { github } from "@/lib/adapters/github";
import { loadRuleset } from "./ruleset-loader";
import type { Review } from "./types";

const VERDICT_BADGE: Record<Review["verdict"], string> = {
  BLOCK: "🛑 **BLOCK**",
  REQUEST_CHANGES: "✋ **REQUEST CHANGES**",
  APPROVE_WITH_NITS: "✅ **APPROVE (with nits)**",
  APPROVE: "✅ **APPROVE**",
  INSUFFICIENT_INFO: "❓ **INSUFFICIENT INFO**",
};

export function buildSummaryMarkdown(review: Review): string {
  const ruleset = loadRuleset();
  const lines: string[] = [];

  lines.push(`## AI EM Copilot — PR Review`);
  lines.push("");
  lines.push(`**Verdict:** ${VERDICT_BADGE[review.verdict]}`);
  lines.push(`**Classification (R1.7):** \`${review.classification}\``);
  lines.push(`**Workflows applied:** ${review.workflowsRun.join(", ")}`);
  lines.push("");
  lines.push(review.summary);
  lines.push("");

  const allFindings = review.results.flatMap((r) => r.findings.map((f) => ({ ...f, workflowId: r.workflowId, workflowTitle: r.workflowTitle })));
  const blocking = allFindings.filter((f) => f.status === "fail" && f.severity === "blocking");
  const warnings = allFindings.filter((f) => f.status === "fail" && f.severity === "warning");
  const nits = allFindings.filter((f) => f.status === "fail" && f.severity === "nit");

  if (blocking.length) {
    lines.push("### 🛑 Blocking issues");
    for (const f of blocking) {
      const rule = ruleset.byId.get(f.ruleId);
      lines.push(`- **${f.ruleId}** (W${f.workflowId} · ${rule?.enforcement ?? ""}): ${truncate(rule?.text ?? "")}`);
      if (f.evidence) lines.push(`  > ${truncate(f.evidence, 300)}`);
    }
    lines.push("");
  }

  if (warnings.length) {
    lines.push("### ⚠️ Should-fix");
    for (const f of warnings) {
      const rule = ruleset.byId.get(f.ruleId);
      lines.push(`- **${f.ruleId}** (W${f.workflowId}): ${truncate(rule?.text ?? "")}`);
      if (f.evidence) lines.push(`  > ${truncate(f.evidence, 200)}`);
    }
    lines.push("");
  }

  if (nits.length) {
    lines.push("<details><summary>📝 Nits (" + nits.length + ")</summary>");
    lines.push("");
    for (const f of nits) lines.push(`- ${f.ruleId}: ${truncate(f.evidence, 160)}`);
    lines.push("");
    lines.push("</details>");
    lines.push("");
  }

  lines.push("<details><summary>Per-workflow summary</summary>");
  lines.push("");
  for (const r of review.results) {
    const fails = r.findings.filter((f) => f.status === "fail").length;
    const passes = r.findings.filter((f) => f.status === "pass").length;
    const nas = r.findings.filter((f) => f.status === "na").length;
    lines.push(`- **W${r.workflowId} ${r.workflowTitle}** — ${passes} pass / ${fails} fail / ${nas} n/a`);
  }
  lines.push("");
  lines.push("</details>");
  lines.push("");
  lines.push("---");
  lines.push(`<sub>Generated by AI EM Copilot. Rules sourced from CODE_REVIEW_RULESET.md (${ruleset.totalRules} rules across ${ruleset.workflows.length} workflows). This is a comment-only review; no merge state was changed.</sub>`);

  return lines.join("\n");
}

function truncate(s: string, n = 220): string {
  if (s.length <= n) return s;
  return s.slice(0, n - 1).trimEnd() + "…";
}

export async function postReview(repo: string, prNumber: number, review: Review): Promise<{ url: string }> {
  return github.postReviewComment(repo, prNumber, buildSummaryMarkdown(review));
}
